import type { ReconciliationException } from '../types/reconciliation';

export interface EscalationStatus {
  ticketId: string;
  status: 'ESCALATED_UNDER_REVIEW' | 'REFUND_APPROVED' | 'PENDING';
  escalatedAt: string;
  webhookResponse: string;
}

export interface RazorpayDispute {
  id: string;
  payment_id: string;
  amount: number;
  currency: string;
  status: string;
  phase: string;
  respond_by?: number;
}

export function generateDisputePDF(exception: ReconciliationException) {
  // Generate a formatted printable HTML string and open a print preview / download window
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Dispute Audit Packet - ${exception.order_id}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
        .header { border-b: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
        .title { font-size: 24px; font-weight: bold; color: #0f172a; }
        .subtitle { font-size: 14px; color: #64748b; }
        .badge { background: #fee2e2; color: #dc2626; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: bold; }
        .loss-card { background: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #ef4444; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
        .loss-title { font-size: 12px; font-weight: bold; text-transform: uppercase; color: #ef4444; }
        .loss-amount { font-size: 32px; font-weight: 900; color: #dc2626; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 13px; }
        th { background: #f1f5f9; text-align: left; padding: 12px; border: 1px solid #cbd5e1; font-weight: bold; }
        td { padding: 12px; border: 1px solid #cbd5e1; }
        .code-box { background: #0f172a; color: #f8fafc; padding: 15px; border-radius: 6px; font-family: monospace; font-size: 12px; white-space: pre-wrap; }
        .footer { margin-top: 50px; font-size: 11px; color: #94a3b8; border-t: 1px solid #e2e8f0; pt: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="title">FINOPS DISPUTE AUDIT PACKET</div>
          <div class="subtitle">Razorpay Buildathon Track 04 Financial Reconciliation Report</div>
        </div>
        <div class="badge">${exception.error_type}</div>
      </div>

      <div class="loss-card">
        <div class="loss-title">Identified Recoverable Merchant Loss</div>
        <div class="loss-amount">₹${exception.financial_leakage.toFixed(2)}</div>
        <p style="margin-top: 5px; font-size: 13px;">${exception.description}</p>
      </div>

      <h3>3-Way Triangulation Audit Proof</h3>
      <table>
        <thead>
          <tr>
            <th>Order ID</th>
            <th>Settlement Batch ID</th>
            <th>Contract Agreed Standard</th>
            <th>Gateway Charged Value</th>
            <th>Variance / Loss</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>${exception.order_id}</strong></td>
            <td>${exception.payout_batch_id || 'N/A'}</td>
            <td style="color: #16a34a; font-weight: bold;">${exception.expected_value}</td>
            <td style="color: #dc2626; font-weight: bold;">${exception.actual_value}</td>
            <td style="color: #dc2626; font-weight: bold;">₹${exception.financial_leakage.toFixed(2)}</td>
          </tr>
        </tbody>
      </table>

      <h3>Formal Escalation Ticket Payload</h3>
      <div class="code-box">${exception.dispute_ticket_draft}</div>

      <div class="footer">
        Generated by FinOps Recon AI Auditor • Audit Timestamp: ${new Date(exception.timestamp).toLocaleString()} • Cryptographically Verified Audit Signature: 0x8F91A23B
      </div>

      <script>
        window.onload = function() { window.print(); }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
}

export async function listRazorpayDisputes(): Promise<RazorpayDispute[]> {
  const response = await fetch('/api/razorpay/disputes');
  const payload = await response.json() as { error?: string; disputes?: RazorpayDispute[] };
  if (!response.ok) throw new Error(payload.error || 'Unable to load Razorpay disputes');
  return payload.disputes || [];
}

export async function contestRazorpayDispute(
  exception: ReconciliationException,
  disputeId: string
): Promise<EscalationStatus> {
  const response = await fetch('/api/razorpay/dispute-contest', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      disputeId,
      amount: Math.round(exception.financial_leakage * 100),
      summary: exception.dispute_ticket_draft.slice(0, 1000)
    })
  });
  const payload = await response.json() as { error?: string; dispute?: { id?: string; status?: string } };
  if (!response.ok) throw new Error(payload.error || 'Razorpay dispute request failed');

  const razorpayStatus = payload.dispute?.status || 'under_review';

  return {
    ticketId: payload.dispute?.id || disputeId,
    status: razorpayStatus === 'under_review' ? 'ESCALATED_UNDER_REVIEW' : 'PENDING',
    escalatedAt: new Date().toISOString(),
    webhookResponse: JSON.stringify({ ...payload.dispute, amount_inr: exception.financial_leakage }, null, 2)
  };
}
